# Generated by Django 3.1.3 on 2020-11-22 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prerequisites', models.ManyToManyField(blank=True, to='coursereview.Course')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('year_taken', models.IntegerField()),
                ('subclass', models.CharField(blank=True, max_length=1)),
                ('professor', models.CharField(max_length=50)),
                ('assessment', models.CharField(blank=True, max_length=50)),
                ('grade', models.IntegerField()),
                ('workload', models.IntegerField()),
                ('review', models.TextField()),
                ('suggestions', models.TextField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursereview.userprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursereview.course')),
            ],
        ),
    ]
