# Generated by Django 3.1.2 on 2020-10-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prerequisites', models.ManyToManyField(blank=True, to='coursereview.Course')),
            ],
        ),
    ]
