# Generated by Django 3.1.2 on 2020-10-27 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursereview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('year_taken', models.IntegerField()),
                ('subclass', models.CharField(max_length=1)),
                ('professor', models.CharField(max_length=50)),
                ('assessment', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=2)),
                ('review', models.TextField()),
                ('suggestions', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursereview.course')),
            ],
        ),
    ]
