# Generated by Django 3.1.2 on 2020-11-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereview', '0005_auto_20201029_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
    ]
