# Generated by Django 3.1.2 on 2020-11-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereview', '0006_auto_20201101_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='subclass',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
