# Generated by Django 3.1.2 on 2020-11-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereview', '0007_auto_20201113_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assessment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
