# Generated by Django 3.1.2 on 2020-11-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereview', '0008_auto_20201115_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
