# Generated by Django 3.1.2 on 2020-11-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereview', '0009_auto_20201115_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='workload',
            field=models.IntegerField(),
        ),
    ]
