# Generated by Django 3.1.2 on 2020-12-06 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursereview', '0010_auto_20201115_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursereview.userprofile')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursereview.review')),
            ],
        ),
    ]
